### ISSUE TITLE
'undef' is not treated as a special value

### ISSUE THREAD

**Issue by roman-alexeev** [puppetlabs/puppet-editor-syntax#66]
<img width="360" alt="Screenshot 2020-06-23 at 12 44 40" src="https://user-images.githubusercontent.com/6114434/85394761-5a490480-b54f-11ea-9517-eaf2406217ff.png">

### What Versions are you running?

OS Version: Catalina
VSCode Version: 1.46.1
Puppet Extension Version: 0.27.3
PDK Version: puppet agent

### What You Are Seeing?

Parsing of comments breaks in certain blocks.
The whole block turns bold (I do not know what this means), and if there's a quote in a comment, it is parsed as an opening quote for a string, which breaks the rest of the file.

I have been able to reproduce it in a block where a comparison with undef happens (other values do not produce this behavior):
```
# This comment is fine
if $var != undef {
    # This comment doesn't  parse properly
    file { 'thing': } 
}
```
### What is Expected?
Pretty obvious

### How Did You Get This To Happen? (Steps to Reproduce)
Open new or existing .pp file.
Type example code from above.

**Comment by glennsarti** [comment]
Moved to editor syntax.

> Pretty obvious

Ha, yeah it is

**Comment by llowder** [comment]
In an epp file, specifically in a templated shell script, comment highlighting breaks inside function blocks.
[screen shot](https://www.dropbox.com/s/jvn5aif7qd4s4it/vscode_puppet_epp_highlight.png?dl=0)

**Comment by glennsarti** [comment]
Directly attaching the image

![image](https://user-images.githubusercontent.com/5819622/85922581-1b9cac80-b8b7-11ea-9f3d-5eb484d8dd74.png)

**Comment by glennsarti** [comment]
@llowder I've moved your issue to #68 as it is not the same as this issue.
